//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISZR.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISZR.Web.RequestMessages", typeof(RequestMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem engedélyezni a felhasználó részére e-mail cím elkészítését, a bv.hu tartományi rendszerben üzemelő szolgáltatások használatához..
        /// </summary>
        public static string E_mail_cím_igénylése {
            get {
                return ResourceManager.GetString("E-mail cím igénylése", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem engedélyezni a felhasználó részére az alábbi a Hikcentral jogosultság kiadását, a kamerarendszer használatához..
        /// </summary>
        public static string HikCentral_jogosultság_igénylése {
            get {
                return ResourceManager.GetString("HikCentral jogosultság igénylése", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem engedélyezni a kamerarendszerben rögzített adatok külső adattárolón történő tárolását, illetve felhasználását megkeresés alapján Bűnügyi vagy Felügyeleti szerv részére..
        /// </summary>
        public static string Kamerafelvétel_lementése {
            get {
                return ResourceManager.GetString("Kamerafelvétel lementése", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem engedélyezni a felhasználó részére többletjogosultság kiadását, a bv.hu tartományi rendszerben üzemelő szolgáltatások használatához..
        /// </summary>
        public static string Meglévő_felhasználó_részére_többletjogosultság {
            get {
                return ResourceManager.GetString("Meglévő felhasználó részére többletjogosultság", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem engedélyezni a felhasználó részére új beosztásának jogosultságainak kiadását, a bv.hu tartományi rendszerben üzemelő szolgáltatások használatához..
        /// </summary>
        public static string Meglévő_felhasználó_új_beosztásának_jogosultságai {
            get {
                return ResourceManager.GetString("Meglévő felhasználó új beosztásának jogosultságai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem engedélyezni a felhasználó részére, az alábbi jármű parkolási engedélyének kiállítását..
        /// </summary>
        public static string Parkolási_engedély_igénylése {
            get {
                return ResourceManager.GetString("Parkolási engedély igénylése", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem engedélyezni a felhasználó részére telefonos PIN kód kiadását, a bv.hu tartományi rendszerben üzemelő szolgáltatások használatához..
        /// </summary>
        public static string Telefonos_PIN_kód_igénylése {
            get {
                return ResourceManager.GetString("Telefonos PIN kód igénylése", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem engedélyezni új felhasználó részére jogosultság kiadását, a bv.hu tartományi rendszerben üzemelő szolgáltatások használatához..
        /// </summary>
        public static string Új_felhasználó_részére_jogosultság_igénylés {
            get {
                return ResourceManager.GetString("Új felhasználó részére jogosultság igénylés", resourceCulture);
            }
        }
    }
}
